services:

  bill-nginx:

    image: nginx:1.29.4-trixie

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.bill.conf:/etc/nginx/conf.d/nginx.bill.conf:ro

    depends_on:
      bill-api:
        condition: service_started

    restart: always

    labels:
      filebeat_enable: "true"
      service: "bill-nginx"